### ISSUE TITLE
Image not uploading correctly

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/everythinghome.homeowner.ai#1]
How can I get the original image of the woman to not display in this header on everythinghome.homeowner.ai/agents page (this is a new subdomain and can be accessed with same support credentials).
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/4b328590-5e6d-4044-803d-b5f879fbc7fa)

**Comment by codextiny** [comment]
Hi @shannonbaldwin ,

i am assuming you guys have already figured it out how to remove image, if you need any other help please let us know...

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/f5ee023c-fd73-4b1e-a976-29850a6fc536)

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/0c116e05-b064-4d62-808b-0124b761fb0c)

**Comment by shannonbaldwin** [comment]
@codextiny Figured it out!
