### ISSUE TITLE
Lines on Home Page

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/everythinghome.homeowner.ai#2]
How do I remove these lines on the home page (everythinghome.homeowner.ai/agents). They were not there before.
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/3bda34b5-5b87-4d54-90fa-3944a07e7a1f)

**Comment by codextiny** [comment]
Hi @shannonbaldwin 

We have removed these lines on your previous everything domain with custom code but i think you didn't purchased the elementor, so we don't have option to add custom style code.

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/fc228f52-1bb3-47d1-adbd-84a5ad6d1e46)

**Comment by shannonbaldwin** [comment]
@codextiny I connected elementor to this account. Please try again?

**Comment by codextiny** [comment]
@shannonbaldwin 

its still showing us to upgrade the elementor ..

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/66518419-ad6b-4c37-8d6c-3d2a8a5f4078)

**Comment by shannonbaldwin** [comment]
@codextiny It is now updated. Sorry about that.

**Comment by codextiny** [comment]
@shannonbaldwin 

We have removed the lines please check and let us know if its still there ...
