### ISSUE TITLE
Video Sizes on Agent Benefits Page

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/everythinghome.homeowner.ai#4]
How can I make the videos larger in size once one of the tiles is clicked on in the media carousel?
URL:[ ](https://everythinghome.homeowner.ai/agents/agent-benefits/)![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/7221a53b-8962-4ac8-8898-dd7c2b7c4c60)

**Comment by codextiny** [comment]
@shannonbaldwin 

We have tried to find out the option to make the video large but cant because its using video link and convert it to iframe so we have used the custom css to make video large.

please check and let us know if you have any issue ..
