### ISSUE TITLE
Spacing on Agent Benefit Page

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/everythinghome.homeowner.ai#5]
How can I decrease spacing here? 
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/38060992-e093-4d9f-9049-813ff28d1368)
[
](https://everythinghome.homeowner.ai/agents/agent-benefits/)

**Comment by codextiny** [comment]
@shannonbaldwin 

you can adjust padding from here, we have adjusted...
see screenshot below:

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/482f080c-99c2-430f-9fe7-e26e3ed43bc1)
