### ISSUE TITLE
Editing an element on How it Works page

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/everythinghome.homeowner.ai#7]
How do I edit the colors of this line on the How it works page?
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/964522d5-b1ca-4339-ae87-47cdf0401b60)
[
](https://everythinghome.homeowner.ai/agents/how-it-works/)

**Comment by codextiny** [comment]
@shannonbaldwin 

edit the column and open border dropdown from sidebar to edit vertical line
 and you can edit the order..
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/0d01dedd-054f-4862-b797-8c2542ec7743)

and for top round shape on vertical line you need to edit second column and select spacer and go to advance setting of spacer and scroll down a bit and edit the border option .
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/dd649a55-34c3-4c6a-afea-56f1a22ee7e1)
