### ISSUE TITLE
Image Issue on How it Works page

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/everythinghome.homeowner.ai#8]
Do you know how to get rid of the shaded border here?
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/69f653fd-4a3a-4551-b7df-bc6eeb51c934)
[
](https://everythinghome.homeowner.ai/agents/how-it-works/)

**Comment by codextiny** [comment]
@shannonbaldwin 

edit the page with elementor
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/33da8a5f-fd6d-4085-98e6-a4de9b07c4dd)

click on image and select style tab
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/76da5f88-52d2-45c3-ba9f-42cc4a2502cf)

and edit/remove border and shadow
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/ffeffb43-9c63-4795-bf1c-7d4c06461250)
