### ISSUE TITLE
Get Started/Claim my Home buttons

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/everythinghome.homeowner.ai#9]
Can you please make sure all of the buttons go to the pop up form, similar to what happens when you click on the "Get Started" button in header of everythinghome.ai?

Bottom of everythinghome.ai: 

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/391d4cdb-f2e2-4baa-8f9e-86cc46ba4be2)

Top of everythinghome.ai/howitworks and bottom 
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/7351373c-768e-493e-a3c7-4b8467199f59)
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/704c28bb-5269-4b99-9fd4-4926aabc5d36)

**Comment by codextiny** [comment]
Hi @shannonbaldwin 

We have added the functionality to open the popup on above mentioned buttons, please have a look and let us know if you have any issue.

added functionality on both pages : everythinghome.ai (1 button), everythinghome.ai/howitworks (2 buttons)

Thanks,
@codextiny
